mqtt:
  verify_ssl: false

vcd:
  host: bos1-vcloud-static-166-227.eng.vmware.com
  log: true
  password: ca$hc0w
  port: 443
  username: administrator
  verify: false

vcs:
- name: vc1
  password: Welcome@123
  username: administrator@vsphere.local
  verify: false

service:
  enforce_authorization: true
  processors: 15
  log_wire: true
  telemetry:
    enable: false
  enable_tkg_plus: true
  legacy_mode: false
  no_vc_communication_mode: false
  register_capvcd_schema: true

broker:
  catalog: cse
  ip_allocation_mode: pool
  network: network1
  org: cseorg
  remote_template_cookbook_url: https://raw.githubusercontent.com/andrew-ni/container-service-extension-templates/ubuntu-20.04-native-template/template_v2.yaml
  storage_profile: '*'
  vdc: cseorg-vdc
